version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ../components/data_preprocessing/logs:/usr/share/logs/data_preprocessing
      - ../components/model_training/logs:/usr/share/logs/model_training
      - ../components/model_deployment/logs:/usr/share/logs/model_deployment 
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"  # Optional port if using beats

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.13.4
    container_name: metricbeat
    user: root
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro

volumes:
  esdata:
