apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ml-pipeline-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium  
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 20

